name: mda-user-guide
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - jupyter_contrib_nbextensions
  - cython
  - numpy
  - nglview
  - sphinx
  - ipywidgets
  - plotly
  - pip
  - pip:
      - sphinx_rtd_theme
      - sphinx-sitemap
      - msmb_theme
      - nbsphinx
      - ipython
      - tabulate
      - sphinxcontrib-bibtex
      - pybtex
      - git+https://github.com/MDAnalysis/mdanalysis@develop#egg=mdanalysis[analysis]&subdirectory=package
      - git+https://github.com/MDAnalysis/mdanalysis@develop#egg=mdanalysistests&subdirectory=testsuite
